config/routes.rb
Rails.application.routes.draw do

  
  resources :enderecos
  resources :compras
  resources :pagamentos
  resources :produtos
  resources :categoria_produtos
  resources :tipo_pagamentos
  resources :compra_has_produtos
  
  get 'signup'  => 'clientes#new' 
  resources :clientes
    
  resources :homes
  
  root 'homes#index'
  
  
  get '/login' => 'session#new'
  post 'login' => 'session#create'
  delete 'logout' => 'session#destroy'

end

app/models/compra_has_produto.rb
class CompraHasProduto < ActiveRecord::Base
  belongs_to :compra
  belongs_to :produto
end

app/controllers/compra_has_produtos_controller.rb
class CompraHasProdutosController < ApplicationController
  before_action :set_compra_has_produto, only: [:show, :edit, :update, :destroy]

  # GET /compra_has_produtos
  # GET /compra_has_produtos.json
  def index
    @compra_has_produtos = CompraHasProduto.all
  end

  # GET /compra_has_produtos/1
  # GET /compra_has_produtos/1.json
  def show
    compra_has_produto = CompraHasProduto.find(@compra_has_produto)
    @produto = Produto.find(compra_has_produto.produto_id)
    
    @compra = Compra.new
  end

  # GET /compra_has_produtos/new
  def new
    @compra_has_produto = CompraHasProduto.new
  end

  # GET /compra_has_produtos/1/edit
  def edit
  end

  # POST /compra_has_produtos
  # POST /compra_has_produtos.json
  def create
    @produto = params[:produto_id]
    @cliente = params[:cliente_id]
    @compra_has_produto = CompraHasProduto.new(compra_has_produto_params)

    respond_to do |format|
      if @compra_has_produto.save
        format.html { redirect_to @compra_has_produto, notice: 'Compra has produto was successfully created.' }
        format.json { render :show, status: :created, location: @compra_has_produto }
      else
        format.html { render :new }
        format.json { render json: @compra_has_produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /compra_has_produtos/1
  # PATCH/PUT /compra_has_produtos/1.json
  def update
    respond_to do |format|
      if @compra_has_produto.update(compra_has_produto_params)
        format.html { redirect_to @compra_has_produto, notice: 'Compra has produto was successfully updated.' }
        format.json { render :show, status: :ok, location: @compra_has_produto }
      else
        format.html { render :edit }
        format.json { render json: @compra_has_produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /compra_has_produtos/1
  # DELETE /compra_has_produtos/1.json
  def destroy
    @compra_has_produto.destroy
    respond_to do |format|
      format.html { redirect_to compra_has_produtos_url, notice: 'Compra has produto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_compra_has_produto
      @compra_has_produto = CompraHasProduto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def compra_has_produto_params
      params.require(:compra_has_produto).permit(:compra_id, :produto_id, :cliente_id)
    end
end

app/helpers/compra_has_produtos_helper.rb
module CompraHasProdutosHelper
end

app/views/compra_has_produtos/_form.html.erb
<%= form_for(@compra_has_produto) do |f| %>
	
  <div class="field">
    <%= f.label :compra_id %><br>
    <%= f.text_field :compra_id %>
  </div>
  <div class="field">
    <%= f.label :produto_id %><br>
    <%= f.text_field :produto_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/compra_has_produtos/edit.html.erb
<h1>Editing Compra Has Produto</h1>

<%= render 'form' %>

<%= link_to 'Show', @compra_has_produto %> |
<%= link_to 'Back', compra_has_produtos_path %>

app/views/compra_has_produtos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Compra Has Produtos</h1>

<table>
  <thead>
    <tr>
      <th>Compra</th>
      <th>Produto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @compra_has_produtos.each do |compra_has_produto| %>
      <tr>
        <td><%= compra_has_produto.compra %></td>
        <td><%= compra_has_produto.produto %></td>
        <td><%= link_to 'Show', compra_has_produto %></td>
        <td><%= link_to 'Edit', edit_compra_has_produto_path(compra_has_produto) %></td>
        <td><%= link_to 'Destroy', compra_has_produto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Compra has produto', new_compra_has_produto_path %>

app/views/compra_has_produtos/new.html.erb
<h1>New Compra Has Produto</h1>

<%= render 'form' %>

<%= link_to 'Back', compra_has_produtos_path %>

app/views/compra_has_produtos/show.html.erb
<p id="notice">
	<%= notice %>
</p>

<div class="row">

	<div class="col s12 m6 l3">
		<div class="card">
			<div class="card-image">
				<%= image_tag @produto.imagem.url(:medium) %>
				<span class="card-title red-text text-darken-4 bold-text"><b><%= @produto.nome%></b></span>
			</div>
			<div class="card-content">
				<p>
					<%= @produto.descricao %>
				</p>
				<p>
					R$ <%= @produto.preco %>
				</p>
			</div>
		</div>
	</div>
	<%= form_for(@compra) do |f| %>
	<div class="col s12 m6 l3">
		<div class="card">
			<div class="card-content">
				<span class="card_title red-text text-darken-4 bold-text"><b>Quantidade</b></span>
				<div class="field">

					<%= text_field_tag :quantidade,nil, :value => 1 %>
				</div>
				<div id="total">

				</div>
			</div>
		</div>

	</div>
	<div class="col s12 m6 l3">
		<div class="card">
			<div class="card-content">
				<span class="card_title red-text text-darken-4 bold-text"><b>Tipo de Pagamento</b></span>
				<div class="field">

					<%= select_tag :tipo_pagamento_id, options_for_select(TipoPagamento::PAGAMENTO.collect {|pg| [pg[0], pg[0]]}), :include_blank => true %>
				</div>
				<div class="field">
					<%= label_tag "Número de Parcelas" %>
					<%= text_field_tag :num_parcelas %>
				</div>
			</div>
		</div>
	</div>
	<div class="col s12 m6 l3">
		<div class="card">
			<div class="card-content">
				<span class="card_title red-text text-darken-4 bold-text"><b>Endereço de Entrega</b></span>
				<div class="field">
					<%= label_tag :rua %>
					<br>
					<%= text_field_tag :rua %>
				</div>
				<div class="field">
					<%= label_tag :bairro %>
					<br>
					<%= text_field_tag :bairro %>
				</div>
				<div class="field">
					<%= label_tag :numero %>
					<br>
					<%= text_field_tag :numero %>
				</div>
				<div class="field">
					<%= label_tag :cidade %>
					<br>
					<%= text_field_tag :cidade %>
				</div>
				<div class="field">
					<%= label_tag :estado %>
					<br>
					<%= select_tag :estado, options_for_select(Endereco::UF.collect {|uf| [uf[0], uf[0]]}), :include_blank => true %>
				</div>
				<div class="actions right-align">
					<button class="btn waves-effect waves-light red darken-4" type="submit" name="action">
						Salvar <i class="material-icons right">add_shopping_cart</i>
					</button>
				</div>
			</div>
		</div>
	</div>
	<% end %>
</div>

<script>

	$(document).ready(function(){
$('#total').html("Valor Total = R$ " + addCommas($('#quantidade').val() * <%= @produto.preco %>) )
$('#quantidade').change(function(){
$('#total').html("Valor Total = R$ " + addCommas($('#quantidade').val() * <%= @produto.preco %>
	) )
	});
	});

	function addCommas(nStr) {
		nStr += '';
		x = nStr.split(',');
		x1 = x[0];
		x2 = x.length > 1 ? ',' + x[1] : '';
		var rgx = /(\d+)(\d{3})/;
		while (rgx.test(x1)) {
			x1 = x1.replace(rgx, '$1' + '.' + '$2');
		}
		return x1 + x2;
	}
</script>