config/routes.rb
Rails.application.routes.draw do

  
  resources :enderecos
  resources :compras
  resources :pagamentos
  resources :produtos
  resources :categoria_produtos
  resources :tipo_pagamentos
  resources :compra_has_produtos
  
  get 'signup'  => 'clientes#new' 
  resources :clientes
    
  resources :homes
  
  root 'homes#index'
  
  
  get '/login' => 'session#new'
  post 'login' => 'session#create'
  delete 'logout' => 'session#destroy'

end

app/models/pagamento.rb
class Pagamento < ActiveRecord::Base
  belongs_to :tipo_pagamento
end

app/controllers/pagamentos_controller.rb
class PagamentosController < ApplicationController
  before_action :set_pagamento, only: [:show, :edit, :update, :destroy]

  # GET /pagamentos
  # GET /pagamentos.json
  def index
    @pagamentos = Pagamento.all
  end

  # GET /pagamentos/1
  # GET /pagamentos/1.json
  def show
  end

  # GET /pagamentos/new
  def new
    @pagamento = Pagamento.new
  end

  # GET /pagamentos/1/edit
  def edit
  end

  # POST /pagamentos
  # POST /pagamentos.json
  def create
    @pagamento = Pagamento.new(pagamento_params)

    respond_to do |format|
      if @pagamento.save
        format.html { redirect_to @pagamento, notice: 'Pagamento was successfully created.' }
        format.json { render :show, status: :created, location: @pagamento }
      else
        format.html { render :new }
        format.json { render json: @pagamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pagamentos/1
  # PATCH/PUT /pagamentos/1.json
  def update
    respond_to do |format|
      if @pagamento.update(pagamento_params)
        format.html { redirect_to @pagamento, notice: 'Pagamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @pagamento }
      else
        format.html { render :edit }
        format.json { render json: @pagamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pagamentos/1
  # DELETE /pagamentos/1.json
  def destroy
    @pagamento.destroy
    respond_to do |format|
      format.html { redirect_to pagamentos_url, notice: 'Pagamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pagamento
      @pagamento = Pagamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pagamento_params
      params.require(:pagamento).permit(:num_parcelas, :tipo_pagamento_id)
    end
end

app/helpers/pagamentos_helper.rb
module PagamentosHelper
end

app/views/pagamentos/_form.html.erb
<%= form_for(@pagamento) do |f| %>
  <% if @pagamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pagamento.errors.count, "error") %> prohibited this pagamento from being saved:</h2>

      <ul>
      <% @pagamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :num_parcelas %><br>
    <%= f.text_field :num_parcelas %>
  </div>
  <div class="field">
    <%= f.label :tipo_pagamento_id %><br>
    <%= f.text_field :tipo_pagamento_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pagamentos/edit.html.erb
<h1>Editing Pagamento</h1>

<%= render 'form' %>

<%= link_to 'Show', @pagamento %> |
<%= link_to 'Back', pagamentos_path %>

app/views/pagamentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pagamentos</h1>

<table>
  <thead>
    <tr>
      <th>Num parcelas</th>
      <th>Tipo pagamento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pagamentos.each do |pagamento| %>
      <tr>
        <td><%= pagamento.num_parcelas %></td>
        <td><%= pagamento.tipo_pagamento %></td>
        <td><%= link_to 'Show', pagamento %></td>
        <td><%= link_to 'Edit', edit_pagamento_path(pagamento) %></td>
        <td><%= link_to 'Destroy', pagamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pagamento', new_pagamento_path %>

app/views/pagamentos/new.html.erb
<h1>New Pagamento</h1>

<%= render 'form' %>

<%= link_to 'Back', pagamentos_path %>

app/views/pagamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Num parcelas:</strong>
  <%= @pagamento.num_parcelas %>
</p>

<p>
  <strong>Tipo pagamento:</strong>
  <%= @pagamento.tipo_pagamento %>
</p>

<%= link_to 'Edit', edit_pagamento_path(@pagamento) %> |
<%= link_to 'Back', pagamentos_path %>