config/routes.rb
Rails.application.routes.draw do

  
  resources :enderecos
  resources :compras
  resources :pagamentos
  resources :produtos
  resources :categoria_produtos
  resources :tipo_pagamentos
  resources :compra_has_produtos
  
  get 'signup'  => 'clientes#new' 
  resources :clientes
    
  resources :homes
  
  root 'homes#index'
  
  
  get '/login' => 'session#new'
  post 'login' => 'session#create'
  delete 'logout' => 'session#destroy'

end

app/models/tipo_pagamento.rb
class TipoPagamento < ActiveRecord::Base
  
   PAGAMENTO = [
    ['Á vista', 0],
    ['Parcelado', 1]
  ]
  
end

app/controllers/tipo_pagamentos_controller.rb
class TipoPagamentosController < ApplicationController
  before_action :set_tipo_pagamento, only: [:show, :edit, :update, :destroy]

  # GET /tipo_pagamentos
  # GET /tipo_pagamentos.json
  def index
    @tipo_pagamentos = TipoPagamento.all
  end

  # GET /tipo_pagamentos/1
  # GET /tipo_pagamentos/1.json
  def show
  end

  # GET /tipo_pagamentos/new
  def new
    @tipo_pagamento = TipoPagamento.new
  end

  # GET /tipo_pagamentos/1/edit
  def edit
  end

  # POST /tipo_pagamentos
  # POST /tipo_pagamentos.json
  def create
    @tipo_pagamento = TipoPagamento.new(tipo_pagamento_params)

    respond_to do |format|
      if @tipo_pagamento.save
        format.html { redirect_to @tipo_pagamento, notice: 'Tipo pagamento was successfully created.' }
        format.json { render :show, status: :created, location: @tipo_pagamento }
      else
        format.html { render :new }
        format.json { render json: @tipo_pagamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_pagamentos/1
  # PATCH/PUT /tipo_pagamentos/1.json
  def update
    respond_to do |format|
      if @tipo_pagamento.update(tipo_pagamento_params)
        format.html { redirect_to @tipo_pagamento, notice: 'Tipo pagamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipo_pagamento }
      else
        format.html { render :edit }
        format.json { render json: @tipo_pagamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_pagamentos/1
  # DELETE /tipo_pagamentos/1.json
  def destroy
    @tipo_pagamento.destroy
    respond_to do |format|
      format.html { redirect_to tipo_pagamentos_url, notice: 'Tipo pagamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_pagamento
      @tipo_pagamento = TipoPagamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_pagamento_params
      params.require(:tipo_pagamento).permit(:tipo)
    end
end

app/helpers/tipo_pagamentos_helper.rb
module TipoPagamentosHelper
end

app/views/tipo_pagamentos/_form.html.erb
<%= form_for(@tipo_pagamento) do |f| %>
  <% if @tipo_pagamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tipo_pagamento.errors.count, "error") %> prohibited this tipo_pagamento from being saved:</h2>

      <ul>
      <% @tipo_pagamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.text_field :tipo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tipo_pagamentos/edit.html.erb
<h1>Editing Tipo Pagamento</h1>

<%= render 'form' %>

<%= link_to 'Show', @tipo_pagamento %> |
<%= link_to 'Back', tipo_pagamentos_path %>

app/views/tipo_pagamentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tipo Pagamentos</h1>

<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tipo_pagamentos.each do |tipo_pagamento| %>
      <tr>
        <td><%= tipo_pagamento.tipo %></td>
        <td><%= link_to 'Show', tipo_pagamento %></td>
        <td><%= link_to 'Edit', edit_tipo_pagamento_path(tipo_pagamento) %></td>
        <td><%= link_to 'Destroy', tipo_pagamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tipo pagamento', new_tipo_pagamento_path %>

app/views/tipo_pagamentos/new.html.erb
<h1>New Tipo Pagamento</h1>

<%= render 'form' %>

<%= link_to 'Back', tipo_pagamentos_path %>

app/views/tipo_pagamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo:</strong>
  <%= @tipo_pagamento.tipo %>
</p>

<%= link_to 'Edit', edit_tipo_pagamento_path(@tipo_pagamento) %> |
<%= link_to 'Back', tipo_pagamentos_path %>