config/routes.rb
Rails.application.routes.draw do

  
  resources :enderecos
  resources :compras
  resources :pagamentos
  resources :produtos
  resources :categoria_produtos
  resources :tipo_pagamentos
  resources :compra_has_produtos
  
  get 'signup'  => 'clientes#new' 
  resources :clientes
    
  resources :homes
  
  root 'homes#index'
  
  
  get '/login' => 'session#new'
  post 'login' => 'session#create'
  delete 'logout' => 'session#destroy'

end

app/models/categoria_produto.rb
class CategoriaProduto < ActiveRecord::Base
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  
  has_secure_password
  before_save :encrypt_password
 
  def encrypt_password
    unless self.password_digest.blank?
      self.password_digest = Digest::SHA1.hexdigest(self.password_digest.to_s)
    end
    return true 
  end
  
end

app/models/compra.rb
class Compra < ActiveRecord::Base
  belongs_to :pagamento
  belongs_to :cliente
end

app/models/compra_has_produto.rb
class CompraHasProduto < ActiveRecord::Base
  belongs_to :compra
  belongs_to :produto
end

app/models/endereco.rb
class Endereco < ActiveRecord::Base
  
  UF = [
    ['Acre (AC)'],
    ['Alagoas (AL)'], 
    ['Amapá (AP)'],
    ['Amazonas (AM)'],
    ['Bahia (BA)'],
    ['Ceará (CE)'],
    ['Distrito Federal (DF)'],
    ['Espírito Santo (ES)'],
    ['Goiás (GO)'],
    ['Maranhão (MA)'],
    ['Mato Grosso (MT)'],
    ['Mato Grosso do Sul (MS)'],
    ['Minas Gerais (MG)'],
    ['Pará (PA) '],
    ['Paraíba (PB)'],
    ['Paraná (PR)'],
    ['Pernambuco (PE)'],
    ['Piauí (PI)'],
    ['Rio de Janeiro (RJ)'],
    ['Rio Grande do Norte (RN)'],
    ['Rio Grande do Sul (RS)'],
    ['Rondônia (RO)'],
    ['Roraima (RR)'],
    ['Santa Catarina (SC)'],
    ['São Paulo (SP)'],
    ['Sergipe (SE)'],
    ['Tocantins (TO)']
  ]
  
end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/pagamento.rb
class Pagamento < ActiveRecord::Base
  belongs_to :tipo_pagamento
end

app/models/produto.rb
class Produto < ActiveRecord::Base
  belongs_to :categoria_produto
  
  
  has_attached_file :imagem, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/missing.jpg"
  do_not_validate_attachment_file_type :imagem
  
  
end

app/models/tipo_pagamento.rb
class TipoPagamento < ActiveRecord::Base
  
   PAGAMENTO = [
    ['Á vista', 0],
    ['Parcelado', 1]
  ]
  
end

app/controllers/compras_controller.rb
class ComprasController < ApplicationController
  before_action :set_compra, only: [:show, :edit, :update, :destroy]

  # GET /compras
  # GET /compras.json
  def index
    @compras = Compra.all
  end

  # GET /compras/1
  # GET /compras/1.json
  def show
  end

  # GET /compras/new
  def new
    @compra = Compra.new
  end

  # GET /compras/1/edit
  def edit
  end

  # POST /compras
  # POST /compras.json
  def create
    @compra = Compra.new(compra_params)

    respond_to do |format|
      if @compra.save
        format.html { redirect_to @compra, notice: 'Compra was successfully created.' }
        format.json { render :show, status: :created, location: @compra }
      else
        format.html { render :new }
        format.json { render json: @compra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /compras/1
  # PATCH/PUT /compras/1.json
  def update
    respond_to do |format|
      if @compra.update(compra_params)
        format.html { redirect_to @compra, notice: 'Compra was successfully updated.' }
        format.json { render :show, status: :ok, location: @compra }
      else
        format.html { render :edit }
        format.json { render json: @compra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /compras/1
  # DELETE /compras/1.json
  def destroy
    @compra.destroy
    respond_to do |format|
      format.html { redirect_to compras_url, notice: 'Compra was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_compra
      @compra = Compra.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def compra_params
      params.require(:compra).permit(:data, :quantidade, :pagamento_id, :cliente_id)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  before_action :require_user, only: [:new, :edit]
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
    @produtos = Produto.all.order(:created_at)
    @compra_has_produto = CompraHasProduto.new
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
    
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.fetch(:home, {})
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new

  end

  def create
    
    @cliente = Cliente.find_by_email(params[:session][:email])
    if @cliente && @cliente.password_digest == Digest::SHA1.hexdigest(params[:session][:password].to_s)
      session[:cliente_id] = @cliente.id
      redirect_to '/'
    else
      redirect_to 'login'
    end
  end

  def destroy
    session[:cliente_id] = nil
    redirect_to '/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/compras_helper.rb
module ComprasHelper
end

app/helpers/enderecos_helper.rb
module EnderecosHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/pagamentos_helper.rb
module PagamentosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Kart</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>

		<header>
			<nav>
				<a href="<%= root_path %>" class="brand-logo">Fast Kart</a>
				<ul id="slide-out" class="side-nav">
					<li>
						<a href="<%= homes_path %>">Principal</a>
					</li>
					<li>
						<a href="#">Carrinho</a>
					</li>
					<li class="no-padding">
						<ul class="collapsible collapsible-accordion">
							<li>
								<a class="collapsible-header">Categorias<i class="mdi-navigation-arrow-drop-down"></i></a>
								<div class="collapsible-body">
									<ul>
										<% @categoria_produtos.each do |categoria|%>
										<li>
											<a href="#"><%= categoria.nome_categoria %></a>
										</li>
										<% end %>
									</ul>
								</div>
							</li>
						</ul>
					</li>
				</ul>
				<ul class="right hide-on-med-and-down">
					<li>
						<a href="<%= homes_path %>">Principal</a>
					</li>
					<li>
						<a href="#">Carrinho</a>
					</li>
					<li>
						<a class="dropdown-button" data-activates="dropdown1">Categorias<i class="mdi-navigation-arrow-drop-down right"></i></a>
					</li>
					<ul id='dropdown1' class='dropdown-content'>
						<% @categoria_produtos.each do |categoria|%>
						<li>
							<a href="#"><%= categoria.nome_categoria%></a>
						</li>
						<% end %>
					</ul>
					<li>
								<% if current_user %>
								<ul>
									<li>
										Bem vindo: <%= current_user.nome %>
									</li>
									<li>
										<%= link_to "Log out", logout_path, method: "delete" %>
									</li>
								</ul>
								<% else %>
								<ul>
									<li>
										<%= link_to "Login", 'login' %></a>
									</li>
									<li>
										<%= link_to "Signup", 'signup' %></a>
									</li>
								</ul>
								<% end %>
							</li>
				</ul>
				<a href="#" data-activates="slide-out" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
			</nav>
		</header>

		<main>
			<div class="container">

				<%= yield %>
			</div>
		</main>

		<footer class="page-footer">
			<div class="container">
				<div class="row">
					<div class="col l6 s12">
						<h5 class="white-text">Footer Content</h5>
						<p class="grey-text text-lighten-4">
							You can use rows and columns here to organize your footer content.
						</p>
					</div>
					<div class="col l4 offset-l2 s12">
						<h5 class="white-text">Links</h5>
						<ul>
							<li>
								<a class="grey-text text-lighten-3" href="<%= produtos_path %>">Produtos</a>
							</li>
							<li>
								<a class="grey-text text-lighten-3" href="<%= categoria_produtos_path %>">Categorias</a>
							</li>
							<li>
								<a class="grey-text text-lighten-3" href="<%= clientes_path %>">Clientes</a>
							</li>
							
						</ul>
					</div>
				</div>
			</div>
			<div class="footer-copyright">
				<div class="container">
					© 2014 Copyright Text
					<a class="grey-text text-lighten-4 right" href="#!">More Links</a>
				</div>
			</div>
		</footer>

	</body>
</html>
<script>
	$(document).ready(function() {

		// Initialize collapse button
		$(".button-collapse").sideNav();
		// Initialize collapsible (uncomment the line below if you use the dropdown variation)
		//$('.collapsible').collapsible();
		$(".dropdown-button").dropdown({
			belowOrigin : true,
			constrain_width : false
		});
		$('select').material_select();
		tinymce.init({
			selector : 'textarea'
		});
	}); 
</script>